<script setup>
import { computed,onMounted,ref } from 'vue'; import { supabase } from '../lib/supabase'; import { getProducts } from '../services/data'; import { useAuth } from '../composables/useAuth'
const products=ref([]),quantities=ref({}),modes=ref({}),draftId=ref(null),loading=ref(true),saving=ref(false),error=ref(''),message=ref(''),started=ref(false),search=ref(''),closed=ref({});const {state}=useAuth()
const filtered=computed(()=>products.value.filter(p=>p.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase())));const groups=computed(()=>filtered.value.reduce((a,p)=>((a[p.category]??=[]).push(p),a),{}));const blankCount=computed(()=>products.value.filter(p=>quantities.value[p.id]===undefined||quantities.value[p.id]==='').length)
onMounted(async()=>{try{products.value=await getProducts(true,false);products.value.forEach(p=>modes.value[p.id]=p.unit)}catch{error.value='Artiklov ni bilo mogoče naložiti.'}finally{loading.value=false}})
function step(p){return Number(p.count_step||1)}function change(p,direction){const now=Number(quantities.value[p.id]||0);quantities.value[p.id]=Math.max(0,Number((now+direction*step(p)).toFixed(3)))}function displayUnit(p){return modes.value[p.id]||p.unit}function enteredBase(p){const q=Number(quantities.value[p.id]);return displayUnit(p)===p.alternative_unit?q*Number(p.alternative_unit_size):q}function changeMode(p,event){const base=enteredBase(p);const next=event.target.value;modes.value[p.id]=next;quantities.value[p.id]=Number((next===p.alternative_unit?base/Number(p.alternative_unit_size):base).toFixed(3))}
async function persist(completed){error.value='';saving.value=true;try{let id=draftId.value;if(!id){id=crypto.randomUUID();const {error:e}=await supabase.from('inventory_counts').insert({id,created_by:state.user.id,status:'draft'});if(e)throw e;draftId.value=id}const rows=products.value.filter(p=>quantities.value[p.id]!==undefined&&quantities.value[p.id]!=='').map(p=>({inventory_count_id:id,product_id:p.id,quantity:enteredBase(p)}));if(rows.length){const {error:e}=await supabase.from('inventory_count_items').upsert(rows,{onConflict:'inventory_count_id,product_id'});if(e)throw e}if(completed){const {error:e}=await supabase.from('inventory_counts').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id);if(e)throw e;message.value=`Popis je zaključen (${rows.length} artiklov).`;draftId.value=null;quantities.value={};started.value=false}else message.value='Osnutek popisa je shranjen.'}catch{error.value='Popisa ni bilo mogoče shraniti. Preverite povezavo in poskusite ponovno.'}finally{saving.value=false}}
async function cancel(){if(!confirm('Prekinem popis? Neshranjeni vnosi bodo izgubljeni.'))return;saving.value=true;error.value='';try{if(draftId.value){const {error:e}=await supabase.from('inventory_counts').delete().eq('id',draftId.value);if(e)throw e}draftId.value=null;quantities.value={};started.value=false;message.value='Popis je prekinjen.'}catch{error.value='Popisa ni bilo mogoče prekiniti. Poskusite ponovno.'}finally{saving.value=false}}
function finish(){if(blankCount.value)message.value=`Še ${blankCount.value} polj je praznih.`;else persist(true)}
</script>
<template><section class="page"><header><p class="eyebrow">ZALOGA</p><h1>Popis</h1></header><div v-if="loading" class="center-state">Nalagam artikle …</div><template v-else-if="!started"><button class="start-card" @click="started=true"><strong>Nov popis</strong><small>Preštejte trenutno zalogo</small><span>›</span></button><RouterLink class="start-card" to="/counts"><strong>Zgodovina popisov</strong><small>Oglejte si zaključene popise</small><span>›</span></RouterLink><p v-if="message" class="success">{{message}}</p></template><template v-else><div class="count-toolbar"><input v-model="search" type="search" placeholder="Poišči izdelek …" aria-label="Poišči izdelek" /><button class="cancel-count" :disabled="saving" @click="cancel">Prekini</button></div><section v-for="(items,category) in groups" :key="category" class="count-group"><button class="category-toggle" @click="closed[category]=!closed[category]"><strong>{{category}}</strong><span>{{closed[category]?'⌄':'⌃'}}</span></button><div v-if="!closed[category]"><article v-for="p in items" :key="p.id" class="counter-item"><strong>{{p.name}}</strong><div class="counter-controls"><select v-if="p.alternative_unit" :value="modes[p.id]" @change="changeMode(p,$event)"><option :value="p.unit">{{p.unit}}</option><option :value="p.alternative_unit">{{p.alternative_unit}} ({{p.alternative_unit_size}} {{p.unit}})</option></select><small v-else>{{p.unit}}</small><button class="minus" @click="change(p,-1)">−</button><input v-model="quantities[p.id]" type="number" min="0" :step="step(p)" inputmode="decimal" :aria-label="p.name" /><button @click="change(p,1)">+</button></div></article></div></section><p v-if="error" class="error">{{error}}</p><p v-if="message" class="success">{{message}}</p><div class="actions"><button class="secondary" :disabled="saving" @click="persist(false)">Shrani osnutek</button><button :disabled="saving" @click="finish">Zaključi popis</button></div><div v-if="message.includes('praznih')" class="detail-overlay"><article class="detail-card"><h2>{{message}}</h2><p>Želite nadaljevati ali zaključiti samo vnesene izdelke?</p><div class="actions"><button class="secondary" @click="persist(true)">Zaključi nepopolno</button><button @click="message=''">Nadaljuj popis</button></div></article></div></template></section></template>
