<script setup>
import { computed,onMounted,ref } from 'vue'
import { supabase } from '../lib/supabase'
import { getProducts,getSuppliers } from '../services/data'
import { useAuth } from '../composables/useAuth'
import ProductForm from '../components/ProductForm.vue'
const products=ref([]),suppliers=ref([]),editing=ref(null),loading=ref(true),saving=ref(false),error=ref(''),message=ref(''),search=ref('')
const {isAdmin}=useAuth(),canEdit=computed(()=>isAdmin())
const empty=()=>({name:'',category:'',unit:'kos',supplier_id:'',lead_time_days:null,safety_stock_quantity:0,active:true,sort_order:0,count_step:1})
const visible=computed(()=>products.value.filter(p=>p.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()))),groups=computed(()=>visible.value.reduce((all,p)=>{(all[p.category]??=[]).push(p);return all},{}))
const date=v=>v?new Date(v).toLocaleDateString('sl-SI'):'—',fmt=v=>v==null?'—':Number(v).toLocaleString('sl-SI',{maximumFractionDigits:1})
async function load(){loading.value=true;try{const[all,supplierList,countsResult,itemsResult,stockResult]=await Promise.all([getProducts(),getSuppliers(),supabase.from('inventory_counts').select('id,completed_at').eq('status','completed').order('completed_at',{ascending:false}),supabase.from('inventory_count_items').select('product_id,quantity,inventory_count_id'),supabase.from('delivery_items').select('product_id,quantity,received_at').not('received_at','is',null)]);if(countsResult.error||itemsResult.error||stockResult.error)throw countsResult.error||itemsResult.error||stockResult.error;const dates=new Map(countsResult.data.map(c=>[c.id,c.completed_at])),last=new Map();for(const i of itemsResult.data){const at=dates.get(i.inventory_count_id),old=last.get(i.product_id);if(at&&(!old||new Date(at)>new Date(old.at)))last.set(i.product_id,{quantity:Number(i.quantity),at})}products.value=all.map(p=>{const count=last.get(p.id),additions=stockResult.data.filter(i=>i.product_id===p.id&&count&&new Date(i.received_at)>new Date(count.at)),newStockQuantity=additions.reduce((sum,i)=>sum+Number(i.quantity),0),lastReceivedAt=additions.sort((a,b)=>new Date(b.received_at)-new Date(a.received_at))[0]?.received_at;return{...p,lastQuantity:count?.quantity,lastCountedAt:count?.at,newStockQuantity,lastReceivedAt,actualQuantity:count?count.quantity+newStockQuantity:null}});suppliers.value=supplierList}catch{error.value='Izdelkov ni bilo mogoče naložiti.'}finally{loading.value=false}}
onMounted(load)
function edit(p){if(canEdit.value)editing.value=p?(editing.value?.id===p.id?null:{...p}):empty()}
async function save(){saving.value=true;error.value='';try{const s=editing.value,payload={name:s.name,category:s.category,unit:s.unit,supplier_id:s.supplier_id||null,lead_time_days:s.lead_time_days===''?null:s.lead_time_days,safety_stock_quantity:Number(s.safety_stock_quantity||0),active:s.active,sort_order:Number(s.sort_order||0),counting_unit:s.counting_unit||null,alternative_unit:s.alternative_unit||null,alternative_unit_size:s.alternative_unit_size||null,count_step:Number(s.count_step||1)};const{error:e}=s.id?await supabase.from('products').update(payload).eq('id',s.id):await supabase.from('products').insert(payload);if(e)throw e;editing.value=null;message.value='Izdelek je shranjen.';await load()}catch{error.value='Izdelka ni bilo mogoče shraniti.'}finally{saving.value=false}}
</script>
<template><section class="page products-page"><header class="products-header"><div><p class="eyebrow">Sladki kot</p><h1>Izdelki</h1><p class="muted">{{products.length}} artiklov v katalogu</p></div><button v-if="canEdit" class="add-product" @click="edit()"><span>＋</span> Dodaj</button></header><div class="product-search"><span>⌕</span><input v-model="search" type="search" placeholder="Poišči izdelek" /></div><p v-if="error" class="error">{{error}}</p><p v-if="message" class="success">{{message}}</p><ProductForm v-if="editing&&!editing.id&&canEdit" v-model="editing" :suppliers="suppliers" :saving="saving" @submit="save" @cancel="editing=null"/><div v-if="loading" class="center-state">Nalagam izdelke …</div><div v-else-if="!visible.length" class="empty-products">Ni izdelkov za ta iskani pojem.</div><section v-else v-for="(items,category) in groups" :key="category" class="product-category"><h2>{{category}}</h2><div class="product-list"><template v-for="p in items" :key="p.id"><component :is="canEdit?'button':'div'" class="product-line" :class="{'product-line--editing':editing?.id===p.id}" @click="edit(p)"><span class="product-name"><span class="product-title">{{p.name}}</span><strong class="current-quantity">{{fmt(p.actualQuantity)}} {{p.unit}}</strong><small>Dejanska zaloga</small></span><span class="product-date"><small>Popis: {{fmt(p.lastQuantity)}} {{p.unit}} · {{date(p.lastCountedAt)}}</small><small v-if="p.lastReceivedAt">Nova zaloga: +{{fmt(p.newStockQuantity)}} {{p.unit}} · {{date(p.lastReceivedAt)}}</small><strong :class="p.active?'product-active':'product-inactive'">{{p.active?'Aktiven':'Neaktiven'}}</strong></span></component><ProductForm v-if="editing?.id===p.id&&canEdit" v-model="editing" class="product-form--inline" :suppliers="suppliers" :saving="saving" @submit="save" @cancel="editing=null"/></template></div></section></section></template>
