export const helpContent = {
  login: { title: 'Prijava v aplikacijo', intro: 'Prijavite se z e-poštnim naslovom in geslom, ki vam ju je dodelil administrator.', tips: ['Če prijava ne uspe, najprej preverite zapis e-pošte in gesla.', 'Po prijavi se prikazane možnosti prilagodijo vaši uporabniški vlogi.'] },
  dashboard: { title: 'Pregled zaloge', intro: 'Pregled razvrsti izdelke glede na ocenjeno količino in čas do ponovnega naročila.', tips: ['»Naroči danes« označuje izdelke z nujno potrebo po naročilu.', 'Odprite skupino in nato izdelek za podrobnosti o porabi, dobavnem roku in varnostni zalogi.', 'Napoved temelji samo na potrjenih popisih in potrjenih novih zalogah.'] },
  countHome: { title: 'Popis zaloge', intro: 'Od tu začnete nov popis ali odprete zgodovino prejšnjih popisov.', tips: ['Če obstaja nezaključen popis iz zadnjih 36 ur, vas aplikacija pred začetkom novega opozori.', 'Za nadaljevanje starega popisa ga najprej odprite v zgodovini in izberite »Prevzemi in nadaljuj«.'] },
  count: { title: 'Nov popis', intro: 'Vnesite trenutno prešteto količino za vsak izdelek in nato oddajte popis v potrditev.', tips: ['Popis se začne shranjevati po prvem vnosu.', 'Če zapustite to stran, se vneseni popis prikaže v zgodovini kot nezaključen.', '»Zavrzi popis« trajno odstrani trenutni osnutek.', 'Oddan popis začne vplivati na zalogo šele, ko ga potrdi administrator.'] },
  counts: { title: 'Zgodovina popisov', intro: 'Tukaj so zbrani nezaključeni, oddani in zaključeni popisi.', tips: ['Nezaključen popis lahko prevzamete in nadaljujete. S košem ga lahko izbriše samo zadnji urejevalec ali administrator.', 'Oddan popis čaka na administratorsko potrditev.', 'Zaključen popis se uporablja pri izračunu dejanske zaloge.', 'Tanek trak kaže delež izdelkov, katerih trenutna popisana vrednost še izvira iz posameznega popisa. Vsi aktivni trakovi skupaj predstavljajo 100 %.'], adminTips: ['Z gumbom »Izvozi popise« ustvarite Excel datoteko z izdelki v vrsticah in popisi v stolpcih. Pred prenosom izvoz potrdite.'] },
  deliveries: { title: 'Naročila in nova zaloga', intro: 'Stran ločuje izdelke na poti od izdelkov, ki so pripravljeni za prevzem v zalogo.', tips: ['Pri naročilu izberite izdelek, količino in predvideni datum. Dobavitelj se vzame iz nastavitev izdelka.', 'Ko nastopi datum dostave, se izdelek premakne pod »Nova zaloga«.', 'Ob prevzemu vnesite dejansko prejeto količino in jo potrdite.', 'S košem odstranite dobavo, ki je ne želite sprejeti, z »Dodaj izdelek« pa evidentirate zalogo brez naročila.'] },
  products: { title: 'Izdelki in dejanska zaloga', intro: 'Dejanska zaloga je zadnja potrjena popisana količina, povečana za potrjene prejeme po tem popisu.', tips: ['Če je popis novejši od prejema, se starejši prejem ne prišteje.', 'Vrstica »Nova zaloga« je prikazana samo, kadar po zadnjem popisu obstaja potrjen prejem.', 'Varnostna zaloga je količina v enoti izdelka, ne število dni.'], adminTips: ['Klik na izdelek odpre obrazec neposredno pod njim.', 'Z gumbom »Izvozi podatke« ustvarite Excel datoteko z dnevno dobavo, porabo in zalogo. Pred prenosom izvoz potrdite.'] },
  suppliers: { title: 'Dobavitelji', intro: 'Dobavitelji hranijo kontaktne podatke in običajni dobavni rok.', tips: ['Izberite dobavitelja za urejanje njegovih podatkov.', 'Dobavitelja nato dodelite izdelku na strani »Izdelki«.', 'Vsak izdelek ima lahko največ enega dobavitelja.'] },
  users: { title: 'Uporabniki', intro: 'Seznam prikazuje uporabnike aplikacije in njihove trenutne vloge.', tips: ['Administrator ima dostop do nastavitev, naročil in potrjevanja popisov.', 'Vloga »Popis zaloge« omogoča izvajanje, oddajo in prevzem popisov.'] },
  more: { title: 'Upravljanje aplikacije', intro: 'Na tej strani so zbrane administratorske nastavitve in povezave do zgodovine.', tips: ['Dobavitelje uredite pred njihovim dodeljevanjem izdelkom.', 'V zgodovini popisov lahko administrator potrdi oddane popise.', 'Gumb »Odjava« varno zaključi trenutno sejo.'] },
  schedule: { title: 'Urnik dela', intro: 'Pregled prikazuje samo načrtovane dneve iz izbranega meseca.', tips: ['Z gumbom »Urejaj« odprete celoten mesec in uredite posamezne dneve.', 'Označite »Zaprto«, kadar Sladki kot ne posluje; ure in zaposleni za ta dan se ne shranijo.', 'Za odprt dan izberite začetek in konec prodaje ter označite sodelujoče.', 'Vsak dan shranite posebej. Urnik je pripravljen za poznejši izračun porabe po delovnih urah.'] },
  default: { title: 'Pomoč', intro: 'Uporabite navigacijo na dnu strani za premikanje med glavnimi deli aplikacije.', tips: ['Vaše možnosti so odvisne od dodeljene uporabniške vloge.'] },
}
export const helpKeyByPath = { '/login':'login','/dashboard':'dashboard','/count':'countHome','/count/new':'count','/history-counts':'counts','/counts':'counts','/deliveries':'deliveries','/products':'products','/suppliers':'suppliers','/users':'users','/more':'more','/schedule':'schedule' }
